### PR TITLE
Oliver/login

### PR DESCRIPTION
**Pull request by oliversong**
This is going to be a ridiculous PR, sorry guys.

I refactored just about everything into sane (hopefully) Express application structure, and changed most of the login code. The good news it that it works!

### CODE REVIEW

**Comment by eob** [comment]
Haha just landed back in Boston and the first sentence of this made me laugh

**Comment by oliversong** [comment]
Heh, welcome back!

**Comment by eob** [comment]
(ps -- will merge in tomorrow so we can have a cool demo at meeting)

**Comment by eob** [comment]
There should be a "Like" button on github comments -- nice going on the Xorigin login!

What ended up being the reason it wasn't working?

**Comment by eob** [comment]
Hey Oliver!

Is that you or should I be worried one of us got hacked?

Hope all is well! You're in SF, right?

Ted

**Comment by oliversong** [comment]
Just me cleaning up old open PRs. Yup, I'm in SF! Hope you're doing well.

**Pull request closed without merging**
